
import type { Upgrade } from '../types/game';

// BALANCED UPGRADES SYSTEM
// - Click upgrades: Additive bonuses instead of multiplicative
// - Global upgrades: Percentage bonuses that add up (not multiply)
// - Helper upgrades: Flat production bonuses instead of multipliers

export const INITIAL_UPGRADES: Upgrade[] = [
  // CLICK UPGRADES - Additive bonuses to click power
  { id: 'better_mouse', name: 'Better Mouse', description: '+1 per click', cost: 100, type: 'CLICK_BONUS', value: 1, purchased: false, icon: '🖱️', category: 'click', condition: { type: 'TOTAL_ENERGY', amount: 50 } },
  { id: 'gaming_mouse', name: 'Gaming Mouse', description: '+2 per click', cost: 500, type: 'CLICK_BONUS', value: 2, purchased: false, icon: '🎮', category: 'click', condition: { type: 'TOTAL_ENERGY', amount: 250 } },
  { id: 'super_mouse', name: 'Super Mouse', description: '+5 per click', cost: 2500, type: 'CLICK_BONUS', value: 5, purchased: false, icon: '⚡', category: 'click', condition: { type: 'TOTAL_ENERGY', amount: 1000 } },
  { id: 'mega_mouse', name: 'Mega Mouse', description: '+10 per click', cost: 15000, type: 'CLICK_BONUS', value: 10, purchased: false, icon: '💎', category: 'click', condition: { type: 'TOTAL_ENERGY', amount: 5000 } },
  { id: 'ultra_mouse', name: 'Ultra Mouse', description: '+25 per click', cost: 100000, type: 'CLICK_BONUS', value: 25, purchased: false, icon: '🌟', category: 'click', condition: { type: 'TOTAL_ENERGY', amount: 50000 } },
  { id: 'master_mouse', name: 'Master Mouse', description: '+100 per click', cost: 1000000, type: 'CLICK_BONUS', value: 100, purchased: false, icon: '👑', category: 'click', condition: { type: 'TOTAL_ENERGY', amount: 500000 } },
  { id: 'legendary_mouse', name: 'Legendary Mouse', description: '+500 per click', cost: 10000000, type: 'CLICK_BONUS', value: 500, purchased: false, icon: '✨', category: 'click', condition: { type: 'TOTAL_ENERGY', amount: 5000000 } },
  { id: 'mythical_mouse', name: 'Mythical Mouse', description: '+2500 per click', cost: 100000000, type: 'CLICK_BONUS', value: 2500, purchased: false, icon: '🌈', category: 'click', condition: { type: 'TOTAL_ENERGY', amount: 50000000 } },

  // GLOBAL UPGRADES - Percentage bonuses (additive)
  { id: 'energy_drink', name: 'Energy Drink', description: 'All +10%', cost: 500, type: 'GLOBAL_PERCENT', value: 10, purchased: false, icon: '🥤', category: 'global', condition: { type: 'TOTAL_ENERGY', amount: 250 } },
  { id: 'coffee_break', name: 'Coffee Break', description: 'All +15%', cost: 3000, type: 'GLOBAL_PERCENT', value: 15, purchased: false, icon: '☕', category: 'global', condition: { type: 'TOTAL_ENERGY', amount: 1500 } },
  { id: 'pokemon_center', name: 'Pokémon Center', description: 'All +20%', cost: 20000, type: 'GLOBAL_PERCENT', value: 20, purchased: false, icon: '🏥', category: 'global', condition: { type: 'TOTAL_ENERGY', amount: 10000 } },
  { id: 'power_plant', name: 'Power Plant', description: 'All +25%', cost: 150000, type: 'GLOBAL_PERCENT', value: 25, purchased: false, icon: '⚡', category: 'global', condition: { type: 'TOTAL_ENERGY', amount: 75000 } },
  { id: 'pokemon_league', name: 'Pokémon League', description: 'All +30%', cost: 1000000, type: 'GLOBAL_PERCENT', value: 30, purchased: false, icon: '🏆', category: 'global', condition: { type: 'TOTAL_ENERGY', amount: 500000 } },
  { id: 'elite_four', name: 'Elite Four', description: 'All +40%', cost: 10000000, type: 'GLOBAL_PERCENT', value: 40, purchased: false, icon: '🎖️', category: 'global', condition: { type: 'TOTAL_ENERGY', amount: 5000000 } },
  { id: 'champion', name: 'Champion', description: 'All +50%', cost: 100000000, type: 'GLOBAL_PERCENT', value: 50, purchased: false, icon: '👑', category: 'global', condition: { type: 'TOTAL_ENERGY', amount: 50000000 } },
  { id: 'pokemon_master', name: 'Pokémon Master', description: 'All +75%', cost: 1000000000, type: 'GLOBAL_PERCENT', value: 75, purchased: false, icon: '🌟', category: 'global', condition: { type: 'TOTAL_ENERGY', amount: 500000000 } },

  // HELPER BASE UPGRADES - Increase base production permanently
  { id: 'pikachu_t1', name: 'Pikachu Training', description: 'Pikachu +0.1/s', cost: 1000, type: 'HELPER_BASE', targetId: 'pikachu', value: 0.1, purchased: false, icon: '⚡', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'pikachu', amount: 10 } },
  { id: 'pikachu_t2', name: 'Thunder Stone', description: 'Pikachu +0.2/s', cost: 5000, type: 'HELPER_BASE', targetId: 'pikachu', value: 0.2, purchased: false, icon: '💎', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'pikachu', amount: 25 } },
  { id: 'charmander_t1', name: 'Charmander Training', description: 'Charmander +1/s', cost: 5000, type: 'HELPER_BASE', targetId: 'charmander', value: 1, purchased: false, icon: '🔥', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'charmander', amount: 10 } },
  { id: 'charmander_t2', name: 'Fire Stone', description: 'Charmander +2/s', cost: 25000, type: 'HELPER_BASE', targetId: 'charmander', value: 2, purchased: false, icon: '💎', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'charmander', amount: 25 } },
  { id: 'squirtle_t1', name: 'Squirtle Training', description: 'Squirtle +8/s', cost: 25000, type: 'HELPER_BASE', targetId: 'squirtle', value: 8, purchased: false, icon: '💧', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'squirtle', amount: 10 } },
  { id: 'squirtle_t2', name: 'Water Stone', description: 'Squirtle +16/s', cost: 150000, type: 'HELPER_BASE', targetId: 'squirtle', value: 16, purchased: false, icon: '💎', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'squirtle', amount: 25 } },
  { id: 'bulbasaur_t1', name: 'Bulbasaur Training', description: 'Bulbasaur +47/s', cost: 150000, type: 'HELPER_BASE', targetId: 'bulbasaur', value: 47, purchased: false, icon: '🌿', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'bulbasaur', amount: 10 } },
  { id: 'bulbasaur_t2', name: 'Leaf Stone', description: 'Bulbasaur +94/s', cost: 1000000, type: 'HELPER_BASE', targetId: 'bulbasaur', value: 94, purchased: false, icon: '💎', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'bulbasaur', amount: 25 } },
  { id: 'eevee_t1', name: 'Eevee Training', description: 'Eevee +260/s', cost: 1000000, type: 'HELPER_BASE', targetId: 'eevee', value: 260, purchased: false, icon: '🦊', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'eevee', amount: 10 } },
  { id: 'eevee_t2', name: 'Evolution Stone', description: 'Eevee +520/s', cost: 7500000, type: 'HELPER_BASE', targetId: 'eevee', value: 520, purchased: false, icon: '💎', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'eevee', amount: 25 } },
  { id: 'gengar_t1', name: 'Gastly Training', description: 'Gastly +1400/s', cost: 7500000, type: 'HELPER_BASE', targetId: 'gengar', value: 1400, purchased: false, icon: '👻', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'gengar', amount: 10 } },
  { id: 'gengar_t2', name: 'Spell Tag', description: 'Gastly +2800/s', cost: 50000000, type: 'HELPER_BASE', targetId: 'gengar', value: 2800, purchased: false, icon: '🏷️', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'gengar', amount: 25 } },
  { id: 'dragonite_t1', name: 'Dratini Training', description: 'Dratini +7800/s', cost: 50000000, type: 'HELPER_BASE', targetId: 'dragonite', value: 7800, purchased: false, icon: '🐉', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'dragonite', amount: 10 } },
  { id: 'dragonite_t2', name: 'Dragon Scale', description: 'Dratini +15600/s', cost: 400000000, type: 'HELPER_BASE', targetId: 'dragonite', value: 15600, purchased: false, icon: '💎', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'dragonite', amount: 25 } },
  { id: 'snorlax_t1', name: 'Munchlax Training', description: 'Munchlax +44K/s', cost: 400000000, type: 'HELPER_BASE', targetId: 'snorlax', value: 44000, purchased: false, icon: '😴', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'snorlax', amount: 10 } },
  { id: 'snorlax_t2', name: 'Leftovers', description: 'Munchlax +88K/s', cost: 3000000000, type: 'HELPER_BASE', targetId: 'snorlax', value: 88000, purchased: false, icon: '🍖', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'snorlax', amount: 25 } },
  { id: 'tyranitar_t1', name: 'Larvitar Training', description: 'Larvitar +260K/s', cost: 3000000000, type: 'HELPER_BASE', targetId: 'tyranitar', value: 260000, purchased: false, icon: '🦖', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'tyranitar', amount: 10 } },
  { id: 'tyranitar_t2', name: 'Dark Stone', description: 'Larvitar +520K/s', cost: 25000000000, type: 'HELPER_BASE', targetId: 'tyranitar', value: 520000, purchased: false, icon: '💎', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'tyranitar', amount: 25 } },
  { id: 'salamence_t1', name: 'Bagon Training', description: 'Bagon +1.6M/s', cost: 25000000000, type: 'HELPER_BASE', targetId: 'salamence', value: 1600000, purchased: false, icon: '🐲', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'salamence', amount: 10 } },
  { id: 'salamence_t2', name: 'Dragon Fang', description: 'Bagon +3.2M/s', cost: 200000000000, type: 'HELPER_BASE', targetId: 'salamence', value: 3200000, purchased: false, icon: '💎', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'salamence', amount: 25 } },
  { id: 'mewtwo_t1', name: 'Mewtwo Training', description: 'Mewtwo +10M/s', cost: 200000000000, type: 'HELPER_BASE', targetId: 'mewtwo', value: 10000000, purchased: false, icon: '🧬', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'mewtwo', amount: 10 } },
  { id: 'mewtwo_t2', name: 'Mega Stone X', description: 'Mewtwo +20M/s', cost: 2000000000000, type: 'HELPER_BASE', targetId: 'mewtwo', value: 20000000, purchased: false, icon: '💎', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'mewtwo', amount: 25 } },
  { id: 'rayquaza_t1', name: 'Rayquaza Training', description: 'Rayquaza +65M/s', cost: 2000000000000, type: 'HELPER_BASE', targetId: 'rayquaza', value: 65000000, purchased: false, icon: '🌪️', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'rayquaza', amount: 10 } },
  { id: 'rayquaza_t2', name: 'Jade Orb', description: 'Rayquaza +130M/s', cost: 20000000000000, type: 'HELPER_BASE', targetId: 'rayquaza', value: 130000000, purchased: false, icon: '💎', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'rayquaza', amount: 25 } },
  { id: 'dialga_t1', name: 'Dialga Training', description: 'Dialga +430M/s', cost: 20000000000000, type: 'HELPER_BASE', targetId: 'dialga', value: 430000000, purchased: false, icon: '⏰', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'dialga', amount: 10 } },
  { id: 'dialga_t2', name: 'Adamant Orb', description: 'Dialga +860M/s', cost: 200000000000000, type: 'HELPER_BASE', targetId: 'dialga', value: 860000000, purchased: false, icon: '💎', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'dialga', amount: 25 } },
  { id: 'arceus_t1', name: 'Arceus Training', description: 'Arceus +2.9B/s', cost: 200000000000000, type: 'HELPER_BASE', targetId: 'arceus', value: 2900000000, purchased: false, icon: '✨', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'arceus', amount: 10 } },
  { id: 'arceus_t2', name: 'Divine Plate', description: 'Arceus +5.8B/s', cost: 2000000000000000, type: 'HELPER_BASE', targetId: 'arceus', value: 5800000000, purchased: false, icon: '🌈', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'arceus', amount: 25 } },
  { id: 'giratina_t1', name: 'Giratina Training', description: 'Giratina +21B/s', cost: 2000000000000000, type: 'HELPER_BASE', targetId: 'giratina', value: 21000000000, purchased: false, icon: '👿', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'giratina', amount: 10 } },
  { id: 'giratina_t2', name: 'Griseous Orb', description: 'Giratina +42B/s', cost: 20000000000000000, type: 'HELPER_BASE', targetId: 'giratina', value: 42000000000, purchased: false, icon: '💎', category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'giratina', amount: 25 } },

  // EVOLUTION UPGRADES - Unlocked when Pokemon evolve
  { id: 'raichu_power', name: 'Raichu Power', description: 'All +5%', cost: 25000, type: 'GLOBAL_PERCENT', value: 5, purchased: false, icon: '⚡', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'pikachu', amount: 25, evolutionName: 'Raichu' } },
  { id: 'charmeleon_fury', name: 'Charmeleon Fury', description: 'Charmander +0.5/s', cost: 15000, type: 'HELPER_BASE', targetId: 'charmander', value: 0.5, purchased: false, icon: '🔥', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'charmander', amount: 15, evolutionName: 'Charmeleon' } },
  { id: 'charizard_blaze', name: 'Charizard Blaze', description: 'All +10%', cost: 200000, type: 'GLOBAL_PERCENT', value: 10, purchased: false, icon: '🔥', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'charmander', amount: 35, evolutionName: 'Charizard' } },
  { id: 'wartortle_shell', name: 'Wartortle Shell', description: 'Squirtle +4/s', cost: 50000, type: 'HELPER_BASE', targetId: 'squirtle', value: 4, purchased: false, icon: '💧', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'squirtle', amount: 15, evolutionName: 'Wartortle' } },
  { id: 'blastoise_hydro', name: 'Blastoise Hydro Pump', description: 'All +10%', cost: 1000000, type: 'GLOBAL_PERCENT', value: 10, purchased: false, icon: '💧', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'squirtle', amount: 35, evolutionName: 'Blastoise' } },
  { id: 'ivysaur_growth', name: 'Ivysaur Growth', description: 'Bulbasaur +23/s', cost: 300000, type: 'HELPER_BASE', targetId: 'bulbasaur', value: 23, purchased: false, icon: '🌿', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'bulbasaur', amount: 15, evolutionName: 'Ivysaur' } },
  { id: 'venusaur_solar', name: 'Venusaur Solar Beam', description: 'All +10%', cost: 5000000, type: 'GLOBAL_PERCENT', value: 10, purchased: false, icon: '🌿', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'bulbasaur', amount: 35, evolutionName: 'Venusaur' } },
  { id: 'vaporeon_aqua', name: 'Vaporeon Aqua Ring', description: 'Eevee +130/s', cost: 2500000, type: 'HELPER_BASE', targetId: 'eevee', value: 130, purchased: false, icon: '💧', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'eevee', amount: 10, evolutionName: 'Vaporeon' } },
  { id: 'jolteon_thunder', name: 'Jolteon Thunder', description: '+50 per click', cost: 15000000, type: 'CLICK_BONUS', value: 50, purchased: false, icon: '⚡', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'eevee', amount: 25, evolutionName: 'Jolteon' } },
  { id: 'flareon_flare', name: 'Flareon Flare Blitz', description: 'All +15%', cost: 50000000, type: 'GLOBAL_PERCENT', value: 15, purchased: false, icon: '🔥', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'eevee', amount: 50, evolutionName: 'Flareon' } },
  { id: 'espeon_psychic', name: 'Espeon Psychic', description: 'All +20%', cost: 200000000, type: 'GLOBAL_PERCENT', value: 20, purchased: false, icon: '🔮', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'eevee', amount: 75, evolutionName: 'Espeon' } },
  { id: 'umbreon_dark', name: 'Umbreon Dark Pulse', description: 'All +25%', cost: 1000000000, type: 'GLOBAL_PERCENT', value: 25, purchased: false, icon: '🌙', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'eevee', amount: 100, evolutionName: 'Umbreon' } },
  { id: 'haunter_curse', name: 'Haunter Curse', description: 'Gastly +700/s', cost: 25000000, type: 'HELPER_BASE', targetId: 'gengar', value: 700, purchased: false, icon: '👻', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'gengar', amount: 15, evolutionName: 'Haunter' } },
  { id: 'gengar_shadow', name: 'Gengar Shadow Ball', description: 'All +15%', cost: 250000000, type: 'GLOBAL_PERCENT', value: 15, purchased: false, icon: '👻', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'gengar', amount: 35, evolutionName: 'Gengar' } },
  { id: 'dragonair_grace', name: 'Dragonair Grace', description: 'Dratini +3900/s', cost: 150000000, type: 'HELPER_BASE', targetId: 'dragonite', value: 3900, purchased: false, icon: '🐉', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'dragonite', amount: 15, evolutionName: 'Dragonair' } },
  { id: 'dragonite_outrage', name: 'Dragonite Outrage', description: 'All +20%', cost: 2000000000, type: 'GLOBAL_PERCENT', value: 20, purchased: false, icon: '🐉', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'dragonite', amount: 35, evolutionName: 'Dragonite' } },
  { id: 'snorlax_rest', name: 'Snorlax Rest', description: 'Munchlax +22K/s', cost: 2000000000, type: 'HELPER_BASE', targetId: 'snorlax', value: 22000, purchased: false, icon: '😴', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'snorlax', amount: 25, evolutionName: 'Snorlax' } },
  { id: 'pupitar_harden', name: 'Pupitar Harden', description: 'Larvitar +130K/s', cost: 15000000000, type: 'HELPER_BASE', targetId: 'tyranitar', value: 130000, purchased: false, icon: '🦖', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'tyranitar', amount: 15, evolutionName: 'Pupitar' } },
  { id: 'tyranitar_crunch', name: 'Tyranitar Crunch', description: 'All +20%', cost: 150000000000, type: 'GLOBAL_PERCENT', value: 20, purchased: false, icon: '🦖', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'tyranitar', amount: 35, evolutionName: 'Tyranitar' } },
  { id: 'shelgon_protect', name: 'Shelgon Protect', description: 'Bagon +800K/s', cost: 100000000000, type: 'HELPER_BASE', targetId: 'salamence', value: 800000, purchased: false, icon: '🐲', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'salamence', amount: 15, evolutionName: 'Shelgon' } },
  { id: 'salamence_fly', name: 'Salamence Fly', description: 'All +25%', cost: 1000000000000, type: 'GLOBAL_PERCENT', value: 25, purchased: false, icon: '🐲', category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'salamence', amount: 35, evolutionName: 'Salamence' } },
];