
import type { Upgrade } from '../types/game';
import { getItemSpriteUrl } from '../utils/itemSprites';

// BALANCED UPGRADES SYSTEM
// - Click upgrades: Additive bonuses instead of multiplicative
// - Global upgrades: Percentage bonuses that add up (not multiply)
// - Helper upgrades: Flat production bonuses instead of multipliers

export const INITIAL_UPGRADES: Upgrade[] = [
  // ============================================
  // CLICK UPGRADES - Poké Balls (unique)
  // ============================================
  { id: 'better_mouse', name: 'Poké Ball', description: '+1 per click', cost: 100, type: 'CLICK_BONUS', value: 1, purchased: false, icon: getItemSpriteUrl('poke-ball'), category: 'click', condition: { type: 'TOTAL_ENERGY', amount: 50 } },
  { id: 'gaming_mouse', name: 'Great Ball', description: '+2 per click', cost: 500, type: 'CLICK_BONUS', value: 2, purchased: false, icon: getItemSpriteUrl('great-ball'), category: 'click', condition: { type: 'TOTAL_ENERGY', amount: 250 } },
  { id: 'super_mouse', name: 'Ultra Ball', description: '+5 per click', cost: 2500, type: 'CLICK_BONUS', value: 5, purchased: false, icon: getItemSpriteUrl('ultra-ball'), category: 'click', condition: { type: 'TOTAL_ENERGY', amount: 1000 } },
  { id: 'mega_mouse', name: 'Master Ball', description: '+10 per click', cost: 15000, type: 'CLICK_BONUS', value: 10, purchased: false, icon: getItemSpriteUrl('master-ball'), category: 'click', condition: { type: 'TOTAL_ENERGY', amount: 5000 } },
  { id: 'ultra_mouse', name: 'Premier Ball', description: '+25 per click', cost: 100000, type: 'CLICK_BONUS', value: 25, purchased: false, icon: getItemSpriteUrl('premier-ball'), category: 'click', condition: { type: 'TOTAL_ENERGY', amount: 50000 } },
  { id: 'master_mouse', name: 'Cherish Ball', description: '+100 per click', cost: 1000000, type: 'CLICK_BONUS', value: 100, purchased: false, icon: getItemSpriteUrl('cherish-ball'), category: 'click', condition: { type: 'TOTAL_ENERGY', amount: 500000 } },
  { id: 'legendary_mouse', name: 'Luxury Ball', description: '+500 per click', cost: 10000000, type: 'CLICK_BONUS', value: 500, purchased: false, icon: getItemSpriteUrl('luxury-ball'), category: 'click', condition: { type: 'TOTAL_ENERGY', amount: 5000000 } },
  { id: 'mythical_mouse', name: 'Safari Ball', description: '+2500 per click', cost: 100000000, type: 'CLICK_BONUS', value: 2500, purchased: false, icon: getItemSpriteUrl('safari-ball'), category: 'click', condition: { type: 'TOTAL_ENERGY', amount: 50000000 } },

  // ============================================
  // GLOBAL UPGRADES - Medicine & Vitamins (unique)
  // ============================================
  { id: 'energy_drink', name: 'Fresh Water', description: 'All +10%', cost: 500, type: 'GLOBAL_PERCENT', value: 10, purchased: false, icon: getItemSpriteUrl('fresh-water'), category: 'global', condition: { type: 'TOTAL_ENERGY', amount: 250 } },
  { id: 'coffee_break', name: 'Moomoo Milk', description: 'All +15%', cost: 3000, type: 'GLOBAL_PERCENT', value: 15, purchased: false, icon: getItemSpriteUrl('moomoo-milk'), category: 'global', condition: { type: 'TOTAL_ENERGY', amount: 1500 } },
  { id: 'pokemon_center', name: 'Full Heal', description: 'All +20%', cost: 20000, type: 'GLOBAL_PERCENT', value: 20, purchased: false, icon: getItemSpriteUrl('full-heal'), category: 'global', condition: { type: 'TOTAL_ENERGY', amount: 10000 } },
  { id: 'power_plant', name: 'Protein', description: 'All +25%', cost: 150000, type: 'GLOBAL_PERCENT', value: 25, purchased: false, icon: getItemSpriteUrl('protein'), category: 'global', condition: { type: 'TOTAL_ENERGY', amount: 75000 } },
  { id: 'pokemon_league', name: 'Rare Candy', description: 'All +30%', cost: 1000000, type: 'GLOBAL_PERCENT', value: 30, purchased: false, icon: getItemSpriteUrl('rare-candy'), category: 'global', condition: { type: 'TOTAL_ENERGY', amount: 500000 } },
  { id: 'elite_four', name: 'PP Max', description: 'All +40%', cost: 10000000, type: 'GLOBAL_PERCENT', value: 40, purchased: false, icon: getItemSpriteUrl('pp-max'), category: 'global', condition: { type: 'TOTAL_ENERGY', amount: 5000000 } },
  { id: 'champion', name: 'Ability Capsule', description: 'All +50%', cost: 100000000, type: 'GLOBAL_PERCENT', value: 50, purchased: false, icon: getItemSpriteUrl('ability-capsule'), category: 'global', condition: { type: 'TOTAL_ENERGY', amount: 50000000 } },
  { id: 'pokemon_master', name: 'Max Elixir', description: 'All +75%', cost: 1000000000, type: 'GLOBAL_PERCENT', value: 75, purchased: false, icon: getItemSpriteUrl('max-elixir'), category: 'global', condition: { type: 'TOTAL_ENERGY', amount: 500000000 } },

  // ============================================
  // HELPER UPGRADES T1 - Type-enhancing items (unique)
  // ============================================
  { id: 'pikachu_t1', name: 'Light Ball', description: 'Pikachu +0.1/s', cost: 1000, type: 'HELPER_BASE', targetId: 'pikachu', value: 0.1, purchased: false, icon: getItemSpriteUrl('light-ball'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'pikachu', amount: 10 } },
  { id: 'pikachu_t2', name: 'Zap Plate', description: 'Pikachu +0.2/s', cost: 5000, type: 'HELPER_BASE', targetId: 'pikachu', value: 0.2, purchased: false, icon: getItemSpriteUrl('zap-plate'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'pikachu', amount: 25 } },
  { id: 'charmander_t1', name: 'Charcoal', description: 'Charmander +1/s', cost: 5000, type: 'HELPER_BASE', targetId: 'charmander', value: 1, purchased: false, icon: getItemSpriteUrl('charcoal'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'charmander', amount: 10 } },
  { id: 'charmander_t2', name: 'Flame Plate', description: 'Charmander +2/s', cost: 25000, type: 'HELPER_BASE', targetId: 'charmander', value: 2, purchased: false, icon: getItemSpriteUrl('flame-plate'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'charmander', amount: 25 } },
  { id: 'squirtle_t1', name: 'Mystic Water', description: 'Squirtle +8/s', cost: 25000, type: 'HELPER_BASE', targetId: 'squirtle', value: 8, purchased: false, icon: getItemSpriteUrl('mystic-water'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'squirtle', amount: 10 } },
  { id: 'squirtle_t2', name: 'Splash Plate', description: 'Squirtle +16/s', cost: 150000, type: 'HELPER_BASE', targetId: 'squirtle', value: 16, purchased: false, icon: getItemSpriteUrl('splash-plate'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'squirtle', amount: 25 } },
  { id: 'bulbasaur_t1', name: 'Miracle Seed', description: 'Bulbasaur +47/s', cost: 150000, type: 'HELPER_BASE', targetId: 'bulbasaur', value: 47, purchased: false, icon: getItemSpriteUrl('miracle-seed'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'bulbasaur', amount: 10 } },
  { id: 'bulbasaur_t2', name: 'Meadow Plate', description: 'Bulbasaur +94/s', cost: 1000000, type: 'HELPER_BASE', targetId: 'bulbasaur', value: 94, purchased: false, icon: getItemSpriteUrl('meadow-plate'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'bulbasaur', amount: 25 } },
  { id: 'meowth_t1', name: 'Amulet Coin', description: 'Meowth +85/s', cost: 200000, type: 'HELPER_BASE', targetId: 'meowth', value: 85, purchased: false, icon: getItemSpriteUrl('amulet-coin'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'meowth', amount: 10 } },
  { id: 'meowth_t2', name: 'Nugget', description: 'Meowth +170/s', cost: 1500000, type: 'HELPER_BASE', targetId: 'meowth', value: 170, purchased: false, icon: getItemSpriteUrl('nugget'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'meowth', amount: 25 } },
  { id: 'machop_t1', name: 'Black Belt', description: 'Machop +150/s', cost: 400000, type: 'HELPER_BASE', targetId: 'machop', value: 150, purchased: false, icon: getItemSpriteUrl('black-belt'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'machop', amount: 10 } },
  { id: 'machop_t2', name: 'Fist Plate', description: 'Machop +300/s', cost: 3000000, type: 'HELPER_BASE', targetId: 'machop', value: 300, purchased: false, icon: getItemSpriteUrl('fist-plate'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'machop', amount: 25 } },
  { id: 'abra_t1', name: 'Twisted Spoon', description: 'Abra +220/s', cost: 750000, type: 'HELPER_BASE', targetId: 'abra', value: 220, purchased: false, icon: getItemSpriteUrl('twisted-spoon'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'abra', amount: 10 } },
  { id: 'abra_t2', name: 'Mind Plate', description: 'Abra +440/s', cost: 6000000, type: 'HELPER_BASE', targetId: 'abra', value: 440, purchased: false, icon: getItemSpriteUrl('mind-plate'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'abra', amount: 25 } },
  { id: 'eevee_t1', name: 'Soothe Bell', description: 'Eevee +260/s', cost: 1000000, type: 'HELPER_BASE', targetId: 'eevee', value: 260, purchased: false, icon: getItemSpriteUrl('soothe-bell'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'eevee', amount: 10 } },
  { id: 'eevee_t2', name: 'Pixie Plate', description: 'Eevee +520/s', cost: 7500000, type: 'HELPER_BASE', targetId: 'eevee', value: 520, purchased: false, icon: getItemSpriteUrl('pixie-plate'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'eevee', amount: 25 } },
  { id: 'gengar_t1', name: 'Spell Tag', description: 'Gastly +1400/s', cost: 7500000, type: 'HELPER_BASE', targetId: 'gengar', value: 1400, purchased: false, icon: getItemSpriteUrl('spell-tag'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'gengar', amount: 10 } },
  { id: 'gengar_t2', name: 'Spooky Plate', description: 'Gastly +2800/s', cost: 50000000, type: 'HELPER_BASE', targetId: 'gengar', value: 2800, purchased: false, icon: getItemSpriteUrl('spooky-plate'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'gengar', amount: 25 } },
  { id: 'dragonite_t1', name: 'Dragon Fang', description: 'Dratini +7800/s', cost: 50000000, type: 'HELPER_BASE', targetId: 'dragonite', value: 7800, purchased: false, icon: getItemSpriteUrl('dragon-fang'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'dragonite', amount: 10 } },
  { id: 'dragonite_t2', name: 'Draco Plate', description: 'Dratini +15600/s', cost: 400000000, type: 'HELPER_BASE', targetId: 'dragonite', value: 15600, purchased: false, icon: getItemSpriteUrl('draco-plate'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'dragonite', amount: 25 } },
  { id: 'snorlax_t1', name: 'Leftovers', description: 'Munchlax +44K/s', cost: 400000000, type: 'HELPER_BASE', targetId: 'snorlax', value: 44000, purchased: false, icon: getItemSpriteUrl('leftovers'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'snorlax', amount: 10 } },
  { id: 'snorlax_t2', name: 'Normal Gem', description: 'Munchlax +88K/s', cost: 3000000000, type: 'HELPER_BASE', targetId: 'snorlax', value: 88000, purchased: false, icon: getItemSpriteUrl('normal-gem'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'snorlax', amount: 25 } },
  { id: 'tyranitar_t1', name: 'Black Glasses', description: 'Larvitar +260K/s', cost: 3000000000, type: 'HELPER_BASE', targetId: 'tyranitar', value: 260000, purchased: false, icon: getItemSpriteUrl('black-glasses'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'tyranitar', amount: 10 } },
  { id: 'tyranitar_t2', name: 'Dread Plate', description: 'Larvitar +520K/s', cost: 25000000000, type: 'HELPER_BASE', targetId: 'tyranitar', value: 520000, purchased: false, icon: getItemSpriteUrl('dread-plate'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'tyranitar', amount: 25 } },
  { id: 'salamence_t1', name: 'Sharp Beak', description: 'Bagon +1.6M/s', cost: 25000000000, type: 'HELPER_BASE', targetId: 'salamence', value: 1600000, purchased: false, icon: getItemSpriteUrl('sharp-beak'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'salamence', amount: 10 } },
  { id: 'salamence_t2', name: 'Sky Plate', description: 'Bagon +3.2M/s', cost: 200000000000, type: 'HELPER_BASE', targetId: 'salamence', value: 3200000, purchased: false, icon: getItemSpriteUrl('sky-plate'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'salamence', amount: 25 } },
  { id: 'mewtwo_t1', name: 'Life Orb', description: 'Mewtwo +10M/s', cost: 200000000000, type: 'HELPER_BASE', targetId: 'mewtwo', value: 10000000, purchased: false, icon: getItemSpriteUrl('life-orb'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'mewtwo', amount: 10 } },
  { id: 'mewtwo_t2', name: 'Mewtwonite X', description: 'Mewtwo +20M/s', cost: 2000000000000, type: 'HELPER_BASE', targetId: 'mewtwo', value: 20000000, purchased: false, icon: getItemSpriteUrl('mewtwonite-x'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'mewtwo', amount: 25 } },
  { id: 'rayquaza_t1', name: 'Dragon Gem', description: 'Rayquaza +65M/s', cost: 2000000000000, type: 'HELPER_BASE', targetId: 'rayquaza', value: 65000000, purchased: false, icon: getItemSpriteUrl('dragon-gem'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'rayquaza', amount: 10 } },
  { id: 'rayquaza_t2', name: 'Jade Orb', description: 'Rayquaza +130M/s', cost: 20000000000000, type: 'HELPER_BASE', targetId: 'rayquaza', value: 130000000, purchased: false, icon: getItemSpriteUrl('jade-orb'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'rayquaza', amount: 25 } },
  { id: 'dialga_t1', name: 'Metal Coat', description: 'Dialga +430M/s', cost: 20000000000000, type: 'HELPER_BASE', targetId: 'dialga', value: 430000000, purchased: false, icon: getItemSpriteUrl('metal-coat'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'dialga', amount: 10 } },
  { id: 'dialga_t2', name: 'Adamant Orb', description: 'Dialga +860M/s', cost: 200000000000000, type: 'HELPER_BASE', targetId: 'dialga', value: 860000000, purchased: false, icon: getItemSpriteUrl('adamant-orb'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'dialga', amount: 25 } },
  { id: 'arceus_t1', name: 'Silk Scarf', description: 'Arceus +2.9B/s', cost: 200000000000000, type: 'HELPER_BASE', targetId: 'arceus', value: 2900000000, purchased: false, icon: getItemSpriteUrl('silk-scarf'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'arceus', amount: 10 } },
  { id: 'arceus_t2', name: 'Blank Plate', description: 'Arceus +5.8B/s', cost: 2000000000000000, type: 'HELPER_BASE', targetId: 'arceus', value: 5800000000, purchased: false, icon: getItemSpriteUrl('blank-plate'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'arceus', amount: 25 } },
  { id: 'giratina_t1', name: 'Reaper Cloth', description: 'Giratina +21B/s', cost: 2000000000000000, type: 'HELPER_BASE', targetId: 'giratina', value: 21000000000, purchased: false, icon: getItemSpriteUrl('reaper-cloth'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'giratina', amount: 10 } },
  { id: 'giratina_t2', name: 'Griseous Orb', description: 'Giratina +42B/s', cost: 20000000000000000, type: 'HELPER_BASE', targetId: 'giratina', value: 42000000000, purchased: false, icon: getItemSpriteUrl('griseous-orb'), category: 'helper', condition: { type: 'HELPER_COUNT', targetId: 'giratina', amount: 25 } },

  // ============================================
  // EVOLUTION UPGRADES - Gems, Mega Stones, unique items
  // ============================================
  { id: 'raichu_power', name: 'Electric Gem', description: 'All +5%', cost: 25000, type: 'GLOBAL_PERCENT', value: 5, purchased: false, icon: getItemSpriteUrl('electric-gem'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'pikachu', amount: 25, evolutionName: 'Raichu' } },
  { id: 'charmeleon_fury', name: 'Fire Gem', description: 'Charmander +0.5/s', cost: 15000, type: 'HELPER_BASE', targetId: 'charmander', value: 0.5, purchased: false, icon: getItemSpriteUrl('fire-gem'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'charmander', amount: 15, evolutionName: 'Charmeleon' } },
  { id: 'charizard_blaze', name: 'Charizardite X', description: 'All +10%', cost: 200000, type: 'GLOBAL_PERCENT', value: 10, purchased: false, icon: getItemSpriteUrl('charizardite-x'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'charmander', amount: 35, evolutionName: 'Charizard' } },
  { id: 'wartortle_shell', name: 'Water Gem', description: 'Squirtle +4/s', cost: 50000, type: 'HELPER_BASE', targetId: 'squirtle', value: 4, purchased: false, icon: getItemSpriteUrl('water-gem'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'squirtle', amount: 15, evolutionName: 'Wartortle' } },
  { id: 'blastoise_hydro', name: 'Blastoisinite', description: 'All +10%', cost: 1000000, type: 'GLOBAL_PERCENT', value: 10, purchased: false, icon: getItemSpriteUrl('blastoisinite'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'squirtle', amount: 35, evolutionName: 'Blastoise' } },
  { id: 'ivysaur_growth', name: 'Grass Gem', description: 'Bulbasaur +23/s', cost: 300000, type: 'HELPER_BASE', targetId: 'bulbasaur', value: 23, purchased: false, icon: getItemSpriteUrl('grass-gem'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'bulbasaur', amount: 15, evolutionName: 'Ivysaur' } },
  { id: 'venusaur_solar', name: 'Venusaurite', description: 'All +10%', cost: 5000000, type: 'GLOBAL_PERCENT', value: 10, purchased: false, icon: getItemSpriteUrl('venusaurite'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'bulbasaur', amount: 35, evolutionName: 'Venusaur' } },
  { id: 'vaporeon_aqua', name: 'Wave Incense', description: 'Eevee +130/s', cost: 2500000, type: 'HELPER_BASE', targetId: 'eevee', value: 130, purchased: false, icon: getItemSpriteUrl('wave-incense'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'eevee', amount: 10, evolutionName: 'Vaporeon' } },
  { id: 'jolteon_thunder', name: 'Magnet', description: '+50 per click', cost: 15000000, type: 'CLICK_BONUS', value: 50, purchased: false, icon: getItemSpriteUrl('magnet'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'eevee', amount: 25, evolutionName: 'Jolteon' } },
  { id: 'flareon_flare', name: 'Heat Rock', description: 'All +15%', cost: 50000000, type: 'GLOBAL_PERCENT', value: 15, purchased: false, icon: getItemSpriteUrl('heat-rock'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'eevee', amount: 50, evolutionName: 'Flareon' } },
  { id: 'espeon_psychic', name: 'Psychic Gem', description: 'All +20%', cost: 200000000, type: 'GLOBAL_PERCENT', value: 20, purchased: false, icon: getItemSpriteUrl('psychic-gem'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'eevee', amount: 75, evolutionName: 'Espeon' } },
  { id: 'umbreon_dark', name: 'Dark Gem', description: 'All +25%', cost: 1000000000, type: 'GLOBAL_PERCENT', value: 25, purchased: false, icon: getItemSpriteUrl('dark-gem'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'eevee', amount: 100, evolutionName: 'Umbreon' } },
  { id: 'haunter_curse', name: 'Ghost Gem', description: 'Gastly +700/s', cost: 25000000, type: 'HELPER_BASE', targetId: 'gengar', value: 700, purchased: false, icon: getItemSpriteUrl('ghost-gem'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'gengar', amount: 15, evolutionName: 'Haunter' } },
  { id: 'gengar_shadow', name: 'Gengarite', description: 'All +15%', cost: 250000000, type: 'GLOBAL_PERCENT', value: 15, purchased: false, icon: getItemSpriteUrl('gengarite'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'gengar', amount: 35, evolutionName: 'Gengar' } },
  { id: 'dragonair_grace', name: 'Dragon Scale', description: 'Dratini +3900/s', cost: 150000000, type: 'HELPER_BASE', targetId: 'dragonite', value: 3900, purchased: false, icon: getItemSpriteUrl('dragon-scale'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'dragonite', amount: 15, evolutionName: 'Dragonair' } },
  { id: 'dragonite_outrage', name: 'Haban Berry', description: 'All +20%', cost: 2000000000, type: 'GLOBAL_PERCENT', value: 20, purchased: false, icon: getItemSpriteUrl('haban-berry'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'dragonite', amount: 35, evolutionName: 'Dragonite' } },
  { id: 'snorlax_rest', name: 'Chesto Berry', description: 'Munchlax +22K/s', cost: 2000000000, type: 'HELPER_BASE', targetId: 'snorlax', value: 22000, purchased: false, icon: getItemSpriteUrl('chesto-berry'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'snorlax', amount: 25, evolutionName: 'Snorlax' } },
  { id: 'pupitar_harden', name: 'Rock Gem', description: 'Larvitar +130K/s', cost: 15000000000, type: 'HELPER_BASE', targetId: 'tyranitar', value: 130000, purchased: false, icon: getItemSpriteUrl('rock-gem'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'tyranitar', amount: 15, evolutionName: 'Pupitar' } },
  { id: 'tyranitar_crunch', name: 'Tyranitarite', description: 'All +20%', cost: 150000000000, type: 'GLOBAL_PERCENT', value: 20, purchased: false, icon: getItemSpriteUrl('tyranitarite'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'tyranitar', amount: 35, evolutionName: 'Tyranitar' } },
  { id: 'shelgon_protect', name: 'Flying Gem', description: 'Bagon +800K/s', cost: 100000000000, type: 'HELPER_BASE', targetId: 'salamence', value: 800000, purchased: false, icon: getItemSpriteUrl('flying-gem'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'salamence', amount: 15, evolutionName: 'Shelgon' } },
  { id: 'salamence_fly', name: 'Salamencite', description: 'All +25%', cost: 1000000000000, type: 'GLOBAL_PERCENT', value: 25, purchased: false, icon: getItemSpriteUrl('salamencite'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'salamence', amount: 35, evolutionName: 'Salamence' } },
  { id: 'persian_payday', name: 'Luck Incense', description: 'Meowth +42/s', cost: 5000000, type: 'HELPER_BASE', targetId: 'meowth', value: 42, purchased: false, icon: getItemSpriteUrl('luck-incense'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'meowth', amount: 28, evolutionName: 'Persian' } },
  { id: 'machoke_strength', name: 'Fighting Gem', description: 'Machop +75/s', cost: 10000000, type: 'HELPER_BASE', targetId: 'machop', value: 75, purchased: false, icon: getItemSpriteUrl('fighting-gem'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'machop', amount: 28, evolutionName: 'Machoke' } },
  { id: 'machamp_might', name: 'Expert Belt', description: 'All +10%', cost: 100000000, type: 'GLOBAL_PERCENT', value: 10, purchased: false, icon: getItemSpriteUrl('expert-belt'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'machop', amount: 40, evolutionName: 'Machamp' } },
  { id: 'kadabra_psychic', name: 'Wise Glasses', description: 'Abra +110/s', cost: 20000000, type: 'HELPER_BASE', targetId: 'abra', value: 110, purchased: false, icon: getItemSpriteUrl('wise-glasses'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'abra', amount: 16, evolutionName: 'Kadabra' } },
  { id: 'alakazam_mind', name: 'Alakazite', description: 'All +15%', cost: 200000000, type: 'GLOBAL_PERCENT', value: 15, purchased: false, icon: getItemSpriteUrl('alakazite'), category: 'evolution', condition: { type: 'EVOLUTION', targetId: 'abra', amount: 35, evolutionName: 'Alakazam' } },
];
